### PR TITLE
Revived for current age

### PR DESCRIPTION
**Pull request by ridercz**
As agreed with @dimapasko, I updated the project to current tooling. No functional changes done (yet), basically all are maintenance tasks to make NConsoler work with .NET Standard and current versions of Visual Studio.

* Removed old tooling, converted for VS 2017/2019 compatibility.
* Formalized coding style, introduced new language features where available.
* Replaced the combiner tool with a batch file and post-build action.
* Converted the project to .NET Standard 2.0
* Added MIT license. I hope it's okay with current maintainers. Currently the project has no licese at all. I like MIT, but any open license will do.
* Updated samples to NetFx 4.7 (4.0 does not support .NET Standard 2.0).
* Added automatic package generation on build.
* Bumped version to 3.0.0-beta01. I feel that .NET Core compatibility warrants major version change.
* Removed NUnit tests for now, as I don't use NUnit and don't know how to make them work with current Visual Studio and wanted to publish cleaned version ASAP. Will add them later.

### CODE REVIEW

**Comment by ivoloshin** [comment]
This is great! I've been using nconsoler for quite a while and it's by far the easiest console parser to use in my opinion.

**Comment by njvsvalhalla** [comment]
The original was an MPL 1.1 license btw, and I don't think it's really possible to change the entire project to MIT. MPL requires any modified files to be licensed as MPL but anything that wasn't part of the original can be MIT)

 https://code.google.com/archive/p/nconsoler/#! (I also worked on this and made it net standard on Friday & did CI to publish to nuget). Tests required minimal modifications to work with the new visual studio for me and latest nunit - besides 2 I had to ignore - what were the issues you were having?

**Comment by dimapasko** [comment]
As one of the original project creators, i will approve this PR and will update license during the weekend

**Comment by ridercz** [comment]
> The original was an MPL 1.1 license btw, and I don't think it's really possible to change the entire project to MIT. MPL requires any modified files to be licensed as MPL but anything that wasn't part of the original can be MIT)- https://code.google.com/archive/p/nconsoler/#!

I was not aware of the old Google Code license specification and the project itself contains no license at all (which is violation of the MPL itself). I think is important that the project would contain _some_ clear open license, but I don't really care which one it will be. I included MIT, because it's simple and permissive but I would leave the licensing issues to original authors.

**Comment by ridercz** [comment]
> (I also worked on this and made it net standard on Friday & did CI to publish to nuget). edit: I realized after what I commented why you were having issues with the test. I just used moq in my fork instead of rhinomocks (feel free to check out my fork)

Great, look like we had the same idea of reviving NConsoler at roughly the same time. Let's see what original authors make out of it over weekend and then we can join forces and make NConsoler live again.

**Pull request merged**
